[[headers]]
  for = "/*"
  [headers.values]
    Content-Type = "application/javascript"
    X-Content-Type-Options = "nosniff"

[build]
  base = "app/kmi-search-tool"
  publish = "dist"
  command = "npm install && npm run build"


[build.environment]
  NODE_VERSION = "16"
